apiVersion: v1
kind: Service
metadata:
  name: fastapi-todo-api-loadbalancer
spec:
  selector:
    app: fastapi-todo-api 
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 8001
      # nodePort: 30008 # Add in if you want specific port on cluster
  type: LoadBalancer