apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-todo-api-deployment
  labels:
    app: fastapi-todo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-todo-api
  template:
    metadata:
      labels:
        app: fastapi-todo-api
    spec:
      containers:
        - name: fastapi-todo-api-container
          image: fastapi_todo_app:1.0.0
          imagePullPolicy: Never #added this so can test with minikube locally
          ports:
          - containerPort: 8001